CREATE WAREHOUSE IF NOT EXISTS AIRCRAFT_WH
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

USE WAREHOUSE AIRCRAFT_WH;

CREATE DATABASE IF NOT EXISTS AIRCRAFT_MAINTENANCE_DB;

USE DATABASE AIRCRAFT_MAINTENANCE_DB;

CREATE SCHEMA IF NOT EXISTS RAW;

USE SCHEMA RAW;

CREATE OR REPLACE TABLE CURATED_MAINTENANCE_EVENTS (
    event_id STRING,
    aircraft_id STRING,
    event_type STRING,
    maintenance_type STRING,
    event_timestamp TIMESTAMP_NTZ,
    severity STRING,
    description STRING,
    source_file STRING,
    loaded_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);