USE WAREHOUSE AIRCRAFT_WH;

USE DATABASE AIRCRAFT_MAINTENANCE_DB;

USE SCHEMA GOLD;

CREATE OR REPLACE TABLE GOLD.DAILY_MAINTENANCE_SUMMARY (
    EVENT_DATE DATE,
    COMPONENT STRING,
    SEVERITY STRING,
    STATUS STRING,
    EVENT_COUNT NUMBER,
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);