SELECT CURRENT_USER(), CURRENT_ROLE(), CURRENT_REGION(), CURRENT_WAREHOUSE(), CURRENT_DATABASE(), CURRENT_SCHEMA();

USE WAREHOUSE AIRCRAFT_WH;

USE DATABASE AIRCRAFT_MAINTENANCE_DB;

USE SCHEMA GOLD;

DESCRIBE TABLE DAILY_MAINTENANCE_SUMMARY;

SHOW COLUMNS IN TABLE DAILY_MAINTENANCE_SUMMARY;

SELECT COUNT(*) FROM DAILY_MAINTENANCE_SUMMARY; 

SELECT * FROM DAILY_MAINTENANCE_SUMMARY LIMIT 20;

