SELECT
    CURRENT_USER(),
    CURRENT_ROLE(),
    CURRENT_REGION(),
    CURRENT_WAREHOUSE(),
    CURRENT_DATABASE(),
    CURRENT_SCHEMA();

USE WAREHOUSE AIRCRAFT_WH;
USE DATABASE AIRCRAFT_MAINTENANCE_DB;
USE SCHEMA GOLD;

SELECT COUNT(*) AS TOTAL_ROWS
FROM DAILY_MAINTENANCE_SUMMARY;

SELECT
    STATUS,
    SUM(EVENT_COUNT) AS TOTAL_EVENTS
FROM DAILY_MAINTENANCE_SUMMARY
GROUP BY STATUS
ORDER BY
    CASE STATUS
        WHEN 'in_progress'  THEN 1
        WHEN 'open'         THEN 2
        ELSE 'closed'       THEN 3
    END;

SELECT
    SEVERITY,
    SUM(EVENT_COUNT) AS TOTAL_EVENTS
FROM DAILY_MAINTENANCE_SUMMARY
WHERE STATUS <> 'closed'
GROUP BY SEVERITY;

SELECT
    COMPONENT,
    SEVERITY,
    SUM(EVENT_COUNT) AS TOTAL_EVENTS
FROM DAILY_MAINTENANCE_SUMMARY
WHERE STATUS <> 'closed'
GROUP BY COMPONENT, SEVERITY
ORDER BY
    COMPONENT,
    CASE SEVERITY
        WHEN 'low'      THEN 1
        WHEN 'medium'   THEN 2
        ELSE 'high'     THEN 3
    END;

SELECT
    COMPONENT,
    STATUS,
    SUM(EVENT_COUNT) AS TOTAL_EVENTS
FROM DAILY_MAINTENANCE_SUMMARY
WHERE STATUS <> 'closed'
GROUP BY COMPONENT, STATUS;