SELECT CURRENT_REGION();

SELECT CURRENT_USER(), CURRENT_ROLE(), CURRENT_WAREHOUSE(), CURRENT_DATABASE(), CURRENT_SCHEMA();

CREATE WAREHOUSE IF NOT EXISTS AIRCRAFT_WH WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;

USE WAREHOUSE AIRCRAFT_WH;

SHOW WAREHOUSES;

CREATE DATABASE IF NOT EXISTS AIRCRAFT_MAINTENANCE_DB;

USE DATABASE AIRCRAFT_MAINTENANCE_DB;

CREATE SCHEMA IF NOT EXISTS GOLD;

SHOW SCHEMAS;

